spring:
  application:
    name: openai
  profiles:
    active:  # spy, pgvector
  config:
    import: "optional:classpath:/creds.yaml"
  ai:
    openai:
      chat:
        options:
          model: "gpt-4o-mini"
management:
  tracing:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: observation
  ai:
    chat:
      client:
        observation:
          include-input: true
      observations:
        include-error-logging: true
    vector:
      store:
        observations:
          include-query-response: true
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  metrics:
    tags:
      application: ${spring.application.name}
  opentelemetry:
    resource-attributes:
      "service.name": ${spring.application.name}
      "service.version": 1.0.0
      "deployment.environment": development
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

---
spring:
  config:
    activate:
      on-profile: spy
  ai:
    openai:
      chat:
        base-url: "http://localhost:7777/openai"

---
spring:
  config:
    activate:
      on-profile: pgvector
  datasource:
    url: jdbc:postgresql://localhost:15432/openai
    username: postgres
    password: password
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
