spring:
  application:
    name: ollama-provider
  profiles:
    active: # spy,pgvector,observation
  ai:
    ollama:
      base-url: "http://localhost:11434/"
      embedding:
        model: nomic-embed-text
      chat:
        model: qwen3
        # model: mistral   # 7B — weak tool calling support
        # model: llama3.2  # 3B — fast but limited structured output / tool calling
        # model: llava     # 7B — multimodal (image+text)
  threads:
    virtual:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: spy
  ai:
    ollama:
      base-url: "http://localhost:7777/ollama"

---
spring:
  config:
    activate:
      on-profile: pgvector
  datasource:
    url: jdbc:postgresql://localhost:15432/ollama
    username: postgres
    password: password
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 768
---
spring:
  config:
    activate:
      on-profile: observation
  ai:
    chat:
      client:
        observation:
          include-input: true
      observations:
        include-error-logging: true
    vector:
      store:
        observations:
          include-query-response: true
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  opentelemetry:
    resource-attributes:
      "service.name": ${spring.application.name}
      "service.version": 1.0.0
      "deployment.environment": development
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        enabled: true
        otlp:
          endpoint: http://localhost:4318/v1/logs
          transport: http
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.example.tracing: DEBUG
