spring:
  config:
    import: "optional:classpath:/creds.yaml"
  profiles:
    active: #pgvector
  ai:
    bedrock:
      aws:
        region: eu-central-1
      converse:
        chat:
          options:
            model: eu.amazon.nova-lite-v1:0
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
