server:
  port: 8083

spring:
  ai:
    mcp:
      server:
        name: 05-mcp-capabilities-server
        version: 0.0.1
        type: SYNC
        protocol: STREAMABLE
        streamable-http:
          mcp-endpoint: /mcp

management:
  endpoints:
    web:
      exposure:
        include: health
